name: Deploy to Local

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if folder exists
        run: |
          if [ -d "C:\laragon\www\pet-food-store" ]; then
            echo "Folder exists"
            rm -rf "C:\laragon\www\pet-food-store"
          else
            echo "Folder does not exist"
          fi
          
       - name: Deploy to Local
        run: cp -r pet-food-store C:\laragon\www\
