name: Deploy to Local

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if folder exists
        run: |
          if (Test-Path -Path "C:\laragon\www\pet-food-store" -PathType Container) {  Remove-Item -Path "C:\laragon\www\pet-food-store"   -Recurse -Force}

          
      - name: Deploy to Local 
        run: cp -r pet-food-store C:\laragon\www\
        
      - name: Set up MySQL
        uses: panyam/setup-mysql@v1
        with:
          mysql-version: 8.x

      - name: Deploy SQL files
        run: |
          for file in sql/*.sql; do
            mysql -h localhost -P 3306 -u root < $file
          done
