name: Sensitive check

on:
  push:
    branches:
      - feature_sensitive_check_06062023

jobs:
  steps:
    - name: Test API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        API_ENDPOINT="https://api.example.com"

        response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $API_KEY" $API_ENDPOINT)

        if [ $response -eq 200 ]; then
          echo "API key is valid."
        else
          echo "API key is invalid."
          exit 1
        fi
